"""add characters

Revision ID: 91cad1a25316
Revises: 
Create Date: 2021-07-14 23:53:59.768852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91cad1a25316'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eng_name', sa.String(length=30), nullable=False),
    sa.Column('eng_link', sa.String(length=200), nullable=False),
    sa.Column('eng_endpoint', sa.String(length=30), nullable=False),
    sa.Column('ru_name', sa.String(length=30), nullable=False),
    sa.Column('ru_link', sa.String(length=200), nullable=False),
    sa.Column('ru_endpoint', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eng_endpoint'),
    sa.UniqueConstraint('eng_link'),
    sa.UniqueConstraint('eng_name'),
    sa.UniqueConstraint('ru_endpoint'),
    sa.UniqueConstraint('ru_link'),
    sa.UniqueConstraint('ru_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
